### ISSUE TITLE
Can not replicate error on `tsc --noEmit`

### ISSUE THREAD

**Issue by developomp** [anyproto/anytype-ts#181]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

PR #179 was reverted in PR #180 due to [`tsc --noEmit` erroring out on every commit](https://github.com/anyproto/anytype-ts/pull/179#issuecomment-1672648481). However, I was not able to replicate the issue on https://github.com/anyproto/anytype-ts/commit/ca07f8b129808c950b828885e77891893f1256b9.

### Expected Behavior

There shouldn't be any tsc error

### Steps To Reproduce

1. Go to ca07f8b129808c950b828885e77891893f1256b9
2. Run `tsc --noEmit`

### Environment

```markdown
- OS: Arch Linux Rolling
- Version: ca07f8b129808c950b828885e77891893f1256b9
```

**Comment by ra3orblade** [comment]
Because you do not have staged files. If you do - you will run into problems with running compiler without config as there are webpack aliases used in code and they generate errors, second thing is that node_modules were not correctly excluded and generate errors as well. I have fixed it, fixed staged linting and commented TSC compiler checks in husky since it is extremely slow and I do not need it on every commit.

**Comment by developomp** [comment]
I believe changes in my PR was not being used when you got the error because as you can see [here](https://github.com/anyproto/anytype-ts/pull/179/files#diff-b55cdbef4907b7045f32cc5360d48d262cca5f94062e353089f189f4460039e0R9), there should not have been errors regarding node_modules yet there were.

Also, I was running `tsc --noEmit` on a terminal emulator so it should not have mattered whether things were git commited or not but regardless, things appear to be fixed now :+1:
